// Autogenerated using mud system-types
import { AttackChargeSystem } from "./ethers-contracts/AttackChargeSystem";
import { AttackFinishSystem } from "./ethers-contracts/AttackFinishSystem";
import { ChangeResourceSeedSystem } from "./ethers-contracts/ChangeResourceSeedSystem";
import { ChangeSeedSystem } from "./ethers-contracts/ChangeSeedSystem";
import { ChangeTreasureSeedSystem } from "./ethers-contracts/ChangeTreasureSeedSystem";
import { DigResourceSystem } from "./ethers-contracts/DigResourceSystem";
import { EncounterFleeSystem } from "./ethers-contracts/EncounterFleeSystem";
import { EncounterThrowSystem } from "./ethers-contracts/EncounterThrowSystem";
import { JoinGameSystem } from "./ethers-contracts/JoinGameSystem";
import { JoinGamev2System } from "./ethers-contracts/JoinGamev2System";
import { MarkSystem } from "./ethers-contracts/MarkSystem";
import { MoveSystem } from "./ethers-contracts/MoveSystem";
import { Movev2System } from "./ethers-contracts/Movev2System";
import { PickUpTreasureSystem } from "./ethers-contracts/PickUpTreasureSystem";
import { TakeResourceSystem } from "./ethers-contracts/TakeResourceSystem";
 
export type SystemTypes = {
  "system.AttackCharge": AttackChargeSystem;
  "system.AttackFinish": AttackFinishSystem;
  "system.ChangeResourceSeed": ChangeResourceSeedSystem;
  "system.ChangeSeed": ChangeSeedSystem;
  "system.ChangeTreasureSeed": ChangeTreasureSeedSystem;
  "system.DigResource": DigResourceSystem;
  "system.EncounterFlee": EncounterFleeSystem;
  "system.EncounterThrow": EncounterThrowSystem;
  "system.JoinGame": JoinGameSystem;
  "system.JoinGamev2": JoinGamev2System;
  "system.Mark": MarkSystem;
  "system.Move": MoveSystem;
  "system.Movev2": Movev2System;
  "system.PickUpTreasure": PickUpTreasureSystem;
  "system.TakeResource": TakeResourceSystem;
};
