// Autogenerated using mud system-types
import AttackChargeSystem from "../abi/AttackChargeSystem.json";
import AttackFinishSystem from "../abi/AttackFinishSystem.json";
import BoundActiveTreasureSystem from "../abi/BoundActiveTreasureSystem.json";
import BuffEffectAddHPCalculateSystem from "../abi/BuffEffectAddHPCalculateSystem.json";
import BuffEffectKeepResourceOnDeathExecuteSystem from "../abi/BuffEffectKeepResourceOnDeathExecuteSystem.json";
import BuildTreasureSystem from "../abi/BuildTreasureSystem.json";
import BulkSetStateSystem from "../abi/BulkSetStateSystem.json";
import ChangeFogSeedSystem from "../abi/ChangeFogSeedSystem.json";
import ChangeResourceSeedSystem from "../abi/ChangeResourceSeedSystem.json";
import ChangeSeedSystem from "../abi/ChangeSeedSystem.json";
import ChangeTreasureSeedSystem from "../abi/ChangeTreasureSeedSystem.json";
import ChargeAirdropTreasureSystem from "../abi/ChargeAirdropTreasureSystem.json";
import ChargeLinearTreasureSystem from "../abi/ChargeLinearTreasureSystem.json";
import ComponentDevSystem from "../abi/ComponentDevSystem.json";
import DigResourceSystem from "../abi/DigResourceSystem.json";
import DigResourcev2System from "../abi/DigResourcev2System.json";
import EncounterFleeSystem from "../abi/EncounterFleeSystem.json";
import EncounterThrowSystem from "../abi/EncounterThrowSystem.json";
import JoinGameSystem from "../abi/JoinGameSystem.json";
import JoinGamev2System from "../abi/JoinGamev2System.json";
import MarkSystem from "../abi/MarkSystem.json";
import MoveSystem from "../abi/MoveSystem.json";
import Movev2System from "../abi/Movev2System.json";
import PickUpTreasureSystem from "../abi/PickUpTreasureSystem.json";
import PickUpTreasurev2System from "../abi/PickUpTreasurev2System.json";
import ReleaseAirdropTreasureSystem from "../abi/ReleaseAirdropTreasureSystem.json";
import ReleaseLinearTreasureSystem from "../abi/ReleaseLinearTreasureSystem.json";
import TakeResourceSystem from "../abi/TakeResourceSystem.json";
import TakeResourcev2System from "../abi/TakeResourcev2System.json";
import TreasureEffectAirdropDefenseSystem from "../abi/TreasureEffectAirdropDefenseSystem.json";
import TreasureEffectAirdropResourceSystem from "../abi/TreasureEffectAirdropResourceSystem.json";
import TreasureEffectDeathKeepResourceSystem from "../abi/TreasureEffectDeathKeepResourceSystem.json";
import TreasureEffectLinearDamageSystem from "../abi/TreasureEffectLinearDamageSystem.json";
import TreasureEffectNegativeAddHPSystem from "../abi/TreasureEffectNegativeAddHPSystem.json";
import UnboundActiveTreasureSystem from "../abi/UnboundActiveTreasureSystem.json";
import UsePassiveTreasureSystem from "../abi/UsePassiveTreasureSystem.json";

export const SystemAbis = {
  "system.AttackCharge": AttackChargeSystem.abi,
  "system.AttackFinish": AttackFinishSystem.abi,
  "system.BoundActiveTreasure": BoundActiveTreasureSystem.abi,
  "system.BuffEffectAddHPCalculate": BuffEffectAddHPCalculateSystem.abi,
  "system.BuffEffectKeepResourceOnDeathExecute": BuffEffectKeepResourceOnDeathExecuteSystem.abi,
  "system.BuildTreasure": BuildTreasureSystem.abi,
  "system.BulkSetState": BulkSetStateSystem.abi,
  "system.ChangeFogSeed": ChangeFogSeedSystem.abi,
  "system.ChangeResourceSeed": ChangeResourceSeedSystem.abi,
  "system.ChangeSeed": ChangeSeedSystem.abi,
  "system.ChangeTreasureSeed": ChangeTreasureSeedSystem.abi,
  "system.ChargeAirdropTreasure": ChargeAirdropTreasureSystem.abi,
  "system.ChargeLinearTreasure": ChargeLinearTreasureSystem.abi,
  "system.ComponentDev": ComponentDevSystem.abi,
  "system.DigResource": DigResourceSystem.abi,
  "system.DigResourcev2": DigResourcev2System.abi,
  "system.EncounterFlee": EncounterFleeSystem.abi,
  "system.EncounterThrow": EncounterThrowSystem.abi,
  "system.JoinGame": JoinGameSystem.abi,
  "system.JoinGamev2": JoinGamev2System.abi,
  "system.Mark": MarkSystem.abi,
  "system.Move": MoveSystem.abi,
  "system.Movev2": Movev2System.abi,
  "system.PickUpTreasure": PickUpTreasureSystem.abi,
  "system.PickUpTreasurev2": PickUpTreasurev2System.abi,
  "system.ReleaseAirdropTreasure": ReleaseAirdropTreasureSystem.abi,
  "system.ReleaseLinearTreasure": ReleaseLinearTreasureSystem.abi,
  "system.TakeResource": TakeResourceSystem.abi,
  "system.TakeResourcev2": TakeResourcev2System.abi,
  "system.TreasureEffectAirdropDefense": TreasureEffectAirdropDefenseSystem.abi,
  "system.TreasureEffectAirdropResource": TreasureEffectAirdropResourceSystem.abi,
  "system.TreasureEffectDeathKeepResource": TreasureEffectDeathKeepResourceSystem.abi,
  "system.TreasureEffectLinearDamage": TreasureEffectLinearDamageSystem.abi,
  "system.TreasureEffectNegativeAddHP": TreasureEffectNegativeAddHPSystem.abi,
  "system.UnboundActiveTreasure": UnboundActiveTreasureSystem.abi,
  "system.UsePassiveTreasure": UsePassiveTreasureSystem.abi,
};
