// Autogenerated using mud system-types
export const systemToId = {
  AttackChargeSystem: "system.AttackCharge",
  DigResourceSystem: "system.DigResource",
  EncounterFleeSystem: "system.EncounterFlee",
  EncounterThrowSystem: "system.EncounterThrow",
  JoinGameSystem: "system.JoinGame",
  JoinGamev2System: "system.JoinGamev2",
  MarkSystem: "system.Mark",
  MoveSystem: "system.Move",
  Movev2System: "system.Movev2",
  PickUpTreasureSystem: "system.PickUpTreasure",
  TakeResourceSystem: "system.TakeResource",
};

export const idToSystem = {
  "system.AttackCharge": "AttackChargeSystem",
  "system.DigResource": "DigResourceSystem",
  "system.EncounterFlee": "EncounterFleeSystem",
  "system.EncounterThrow": "EncounterThrowSystem",
  "system.JoinGame": "JoinGameSystem",
  "system.JoinGamev2": "JoinGamev2System",
  "system.Mark": "MarkSystem",
  "system.Move": "MoveSystem",
  "system.Movev2": "Movev2System",
  "system.PickUpTreasure": "PickUpTreasureSystem",
  "system.TakeResource": "TakeResourceSystem",
};
  