// Autogenerated using mud system-types
import AttackChargeSystem from "../abi/AttackChargeSystem.json";
import AttackFinishSystem from "../abi/AttackFinishSystem.json";
import ChangeFogSeedSystem from "../abi/ChangeFogSeedSystem.json";
import ChangeResourceSeedSystem from "../abi/ChangeResourceSeedSystem.json";
import ChangeSeedSystem from "../abi/ChangeSeedSystem.json";
import ChangeTreasureSeedSystem from "../abi/ChangeTreasureSeedSystem.json";
import DigResourceSystem from "../abi/DigResourceSystem.json";
import EncounterFleeSystem from "../abi/EncounterFleeSystem.json";
import EncounterThrowSystem from "../abi/EncounterThrowSystem.json";
import JoinGameSystem from "../abi/JoinGameSystem.json";
import JoinGamev2System from "../abi/JoinGamev2System.json";
import MarkSystem from "../abi/MarkSystem.json";
import MoveSystem from "../abi/MoveSystem.json";
import Movev2System from "../abi/Movev2System.json";
import PickUpTreasureSystem from "../abi/PickUpTreasureSystem.json";
import TakeResourceSystem from "../abi/TakeResourceSystem.json";

export const SystemAbis = {
  "system.AttackCharge": AttackChargeSystem.abi,
  "system.AttackFinish": AttackFinishSystem.abi,
  "system.ChangeFogSeed": ChangeFogSeedSystem.abi,
  "system.ChangeResourceSeed": ChangeResourceSeedSystem.abi,
  "system.ChangeSeed": ChangeSeedSystem.abi,
  "system.ChangeTreasureSeed": ChangeTreasureSeedSystem.abi,
  "system.DigResource": DigResourceSystem.abi,
  "system.EncounterFlee": EncounterFleeSystem.abi,
  "system.EncounterThrow": EncounterThrowSystem.abi,
  "system.JoinGame": JoinGameSystem.abi,
  "system.JoinGamev2": JoinGamev2System.abi,
  "system.Mark": MarkSystem.abi,
  "system.Move": MoveSystem.abi,
  "system.Movev2": Movev2System.abi,
  "system.PickUpTreasure": PickUpTreasureSystem.abi,
  "system.TakeResource": TakeResourceSystem.abi,
};
