// Autogenerated using mud system-types
import AdjustGuildMemberSystem from "../abi/AdjustGuildMemberSystem.json";
import AllocateResourceSystem from "../abi/AllocateResourceSystem.json";
import AllocateTreasureSystem from "../abi/AllocateTreasureSystem.json";
import ApproveGuildSystem from "../abi/ApproveGuildSystem.json";
import AttackChargeSystem from "../abi/AttackChargeSystem.json";
import AttackFinishSystem from "../abi/AttackFinishSystem.json";
import AttackFinishv2System from "../abi/AttackFinishv2System.json";
import BoundTreasureSystem from "../abi/BoundTreasureSystem.json";
import BuffEffectAddHPCalculateSystem from "../abi/BuffEffectAddHPCalculateSystem.json";
import BuffEffectKeepResourceOnDeathExecuteSystem from "../abi/BuffEffectKeepResourceOnDeathExecuteSystem.json";
import BuildTreasureSystem from "../abi/BuildTreasureSystem.json";
import BulkSetStateSystem from "../abi/BulkSetStateSystem.json";
import BuyResourceBuildingSystem from "../abi/BuyResourceBuildingSystem.json";
import ChangeFogSeedSystem from "../abi/ChangeFogSeedSystem.json";
import ChangeGuildDisplaySystem from "../abi/ChangeGuildDisplaySystem.json";
import ChangeResourceSeedSystem from "../abi/ChangeResourceSeedSystem.json";
import ChangeSeedSystem from "../abi/ChangeSeedSystem.json";
import ChangeTreasureSeedSystem from "../abi/ChangeTreasureSeedSystem.json";
import ChargeAirdropTreasureSystem from "../abi/ChargeAirdropTreasureSystem.json";
import ChargeLinearTreasureSystem from "../abi/ChargeLinearTreasureSystem.json";
import CloseDevSystem from "../abi/CloseDevSystem.json";
import ComponentDevSystem from "../abi/ComponentDevSystem.json";
import CreateGuildSystem from "../abi/CreateGuildSystem.json";
import DeathTriggerSystem from "../abi/DeathTriggerSystem.json";
import DigResourceBuildingSystem from "../abi/DigResourceBuildingSystem.json";
import DigResourceSystem from "../abi/DigResourceSystem.json";
import DigResourcev2System from "../abi/DigResourcev2System.json";
import DonateResourceSystem from "../abi/DonateResourceSystem.json";
import DonateTreasureSystem from "../abi/DonateTreasureSystem.json";
import EditGuildSystem from "../abi/EditGuildSystem.json";
import EncounterFleeSystem from "../abi/EncounterFleeSystem.json";
import EncounterThrowSystem from "../abi/EncounterThrowSystem.json";
import GuildBoundTreasureSystem from "../abi/GuildBoundTreasureSystem.json";
import GuildBuildTreasureSystem from "../abi/GuildBuildTreasureSystem.json";
import GuildChargeAirdropTreasureSystem from "../abi/GuildChargeAirdropTreasureSystem.json";
import GuildChargeLinearTreasureSystem from "../abi/GuildChargeLinearTreasureSystem.json";
import GuildMoveSystem from "../abi/GuildMoveSystem.json";
import GuildReleaseAirdropTreasureSystem from "../abi/GuildReleaseAirdropTreasureSystem.json";
import GuildReleaseLinearTreasureSystem from "../abi/GuildReleaseLinearTreasureSystem.json";
import GuildTechAccelerateSystem from "../abi/GuildTechAccelerateSystem.json";
import GuildTechCancelSystem from "../abi/GuildTechCancelSystem.json";
import GuildTechFinishSystem from "../abi/GuildTechFinishSystem.json";
import GuildTechUpdateSystem from "../abi/GuildTechUpdateSystem.json";
import GuildUnboundTreasureSystem from "../abi/GuildUnboundTreasureSystem.json";
import JoinGameSystem from "../abi/JoinGameSystem.json";
import JoinGamev2System from "../abi/JoinGamev2System.json";
import JoinGuildSystem from "../abi/JoinGuildSystem.json";
import KickGuildMemberSystem from "../abi/KickGuildMemberSystem.json";
import MarkSystem from "../abi/MarkSystem.json";
import MoveSystem from "../abi/MoveSystem.json";
import Movev2System from "../abi/Movev2System.json";
import PickUpRuinSystem from "../abi/PickUpRuinSystem.json";
import PickUpTreasureSystem from "../abi/PickUpTreasureSystem.json";
import PickUpTreasurev2System from "../abi/PickUpTreasurev2System.json";
import RejectGuildSystem from "../abi/RejectGuildSystem.json";
import ReleaseAirdropTreasureSystem from "../abi/ReleaseAirdropTreasureSystem.json";
import ReleaseLinearTreasureSystem from "../abi/ReleaseLinearTreasureSystem.json";
import ResourceDevSystem from "../abi/ResourceDevSystem.json";
import SetResourceConfigSystem from "../abi/SetResourceConfigSystem.json";
import SetStatusSystem from "../abi/SetStatusSystem.json";
import SettleResourceBuildingSystem from "../abi/SettleResourceBuildingSystem.json";
import TakeResourceBuildingSystem from "../abi/TakeResourceBuildingSystem.json";
import TakeResourceSystem from "../abi/TakeResourceSystem.json";
import TakeResourcev2System from "../abi/TakeResourcev2System.json";
import TechAccelerateSystem from "../abi/TechAccelerateSystem.json";
import TechCancelSystem from "../abi/TechCancelSystem.json";
import TechEffectAddHPSystem from "../abi/TechEffectAddHPSystem.json";
import TechEffectExtraResourceSystem from "../abi/TechEffectExtraResourceSystem.json";
import TechFinishSystem from "../abi/TechFinishSystem.json";
import TechUpdateSystem from "../abi/TechUpdateSystem.json";
import TransferGuildLeaderSystem from "../abi/TransferGuildLeaderSystem.json";
import TreasureEffectAirdropDefenseSystem from "../abi/TreasureEffectAirdropDefenseSystem.json";
import TreasureEffectAirdropResourceSystem from "../abi/TreasureEffectAirdropResourceSystem.json";
import TreasureEffectDeathKeepResourceSystem from "../abi/TreasureEffectDeathKeepResourceSystem.json";
import TreasureEffectLinearDamageSystem from "../abi/TreasureEffectLinearDamageSystem.json";
import TreasureEffectNegativeAddHPSystem from "../abi/TreasureEffectNegativeAddHPSystem.json";
import UnboundTreasureSystem from "../abi/UnboundTreasureSystem.json";

export const SystemAbis = {
  "system.AdjustGuildMember": AdjustGuildMemberSystem.abi,
  "system.AllocateResource": AllocateResourceSystem.abi,
  "system.AllocateTreasure": AllocateTreasureSystem.abi,
  "system.ApproveGuild": ApproveGuildSystem.abi,
  "system.AttackCharge": AttackChargeSystem.abi,
  "system.AttackFinish": AttackFinishSystem.abi,
  "system.AttackFinishv2": AttackFinishv2System.abi,
  "system.BoundTreasure": BoundTreasureSystem.abi,
  "system.BuffEffectAddHPCalculate": BuffEffectAddHPCalculateSystem.abi,
  "system.BuffEffectKeepResourceOnDeathExecute": BuffEffectKeepResourceOnDeathExecuteSystem.abi,
  "system.BuildTreasure": BuildTreasureSystem.abi,
  "system.BulkSetState": BulkSetStateSystem.abi,
  "system.BuyResourceBuilding": BuyResourceBuildingSystem.abi,
  "system.ChangeFogSeed": ChangeFogSeedSystem.abi,
  "system.ChangeGuildDisplay": ChangeGuildDisplaySystem.abi,
  "system.ChangeResourceSeed": ChangeResourceSeedSystem.abi,
  "system.ChangeSeed": ChangeSeedSystem.abi,
  "system.ChangeTreasureSeed": ChangeTreasureSeedSystem.abi,
  "system.ChargeAirdropTreasure": ChargeAirdropTreasureSystem.abi,
  "system.ChargeLinearTreasure": ChargeLinearTreasureSystem.abi,
  "system.CloseDev": CloseDevSystem.abi,
  "system.ComponentDev": ComponentDevSystem.abi,
  "system.CreateGuild": CreateGuildSystem.abi,
  "system.DeathTrigger": DeathTriggerSystem.abi,
  "system.DigResourceBuilding": DigResourceBuildingSystem.abi,
  "system.DigResource": DigResourceSystem.abi,
  "system.DigResourcev2": DigResourcev2System.abi,
  "system.DonateResource": DonateResourceSystem.abi,
  "system.DonateTreasure": DonateTreasureSystem.abi,
  "system.EditGuild": EditGuildSystem.abi,
  "system.EncounterFlee": EncounterFleeSystem.abi,
  "system.EncounterThrow": EncounterThrowSystem.abi,
  "system.GuildBoundTreasure": GuildBoundTreasureSystem.abi,
  "system.GuildBuildTreasure": GuildBuildTreasureSystem.abi,
  "system.GuildChargeAirdropTreasure": GuildChargeAirdropTreasureSystem.abi,
  "system.GuildChargeLinearTreasure": GuildChargeLinearTreasureSystem.abi,
  "system.GuildMove": GuildMoveSystem.abi,
  "system.GuildReleaseAirdropTreasure": GuildReleaseAirdropTreasureSystem.abi,
  "system.GuildReleaseLinearTreasure": GuildReleaseLinearTreasureSystem.abi,
  "system.GuildTechAccelerate": GuildTechAccelerateSystem.abi,
  "system.GuildTechCancel": GuildTechCancelSystem.abi,
  "system.GuildTechFinish": GuildTechFinishSystem.abi,
  "system.GuildTechUpdate": GuildTechUpdateSystem.abi,
  "system.GuildUnboundTreasure": GuildUnboundTreasureSystem.abi,
  "system.JoinGame": JoinGameSystem.abi,
  "system.JoinGamev2": JoinGamev2System.abi,
  "system.JoinGuild": JoinGuildSystem.abi,
  "system.KickGuildMember": KickGuildMemberSystem.abi,
  "system.Mark": MarkSystem.abi,
  "system.Move": MoveSystem.abi,
  "system.Movev2": Movev2System.abi,
  "system.PickUpRuin": PickUpRuinSystem.abi,
  "system.PickUpTreasure": PickUpTreasureSystem.abi,
  "system.PickUpTreasurev2": PickUpTreasurev2System.abi,
  "system.RejectGuild": RejectGuildSystem.abi,
  "system.ReleaseAirdropTreasure": ReleaseAirdropTreasureSystem.abi,
  "system.ReleaseLinearTreasure": ReleaseLinearTreasureSystem.abi,
  "system.ResourceDev": ResourceDevSystem.abi,
  "system.SetResourceConfig": SetResourceConfigSystem.abi,
  "system.SetStatus": SetStatusSystem.abi,
  "system.SettleResourceBuilding": SettleResourceBuildingSystem.abi,
  "system.TakeResourceBuilding": TakeResourceBuildingSystem.abi,
  "system.TakeResource": TakeResourceSystem.abi,
  "system.TakeResourcev2": TakeResourcev2System.abi,
  "system.TechAccelerate": TechAccelerateSystem.abi,
  "system.TechCancel": TechCancelSystem.abi,
  "system.TechEffectAddHP": TechEffectAddHPSystem.abi,
  "system.TechEffectExtraResource": TechEffectExtraResourceSystem.abi,
  "system.TechFinish": TechFinishSystem.abi,
  "system.TechUpdate": TechUpdateSystem.abi,
  "system.TransferGuildLeader": TransferGuildLeaderSystem.abi,
  "system.TreasureEffectAirdropDefense": TreasureEffectAirdropDefenseSystem.abi,
  "system.TreasureEffectAirdropResource": TreasureEffectAirdropResourceSystem.abi,
  "system.TreasureEffectDeathKeepResource": TreasureEffectDeathKeepResourceSystem.abi,
  "system.TreasureEffectLinearDamage": TreasureEffectLinearDamageSystem.abi,
  "system.TreasureEffectNegativeAddHP": TreasureEffectNegativeAddHPSystem.abi,
  "system.UnboundTreasure": UnboundTreasureSystem.abi,
};
