// Autogenerated using mud system-types
import EncounterFleeSystem from "../abi/EncounterFleeSystem.json";
import EncounterThrowSystem from "../abi/EncounterThrowSystem.json";
import JoinGameSystem from "../abi/JoinGameSystem.json";
import JoinGamev2System from "../abi/JoinGamev2System.json";
import MarkSystem from "../abi/MarkSystem.json";
import MoveSystem from "../abi/MoveSystem.json";
import Movev2System from "../abi/Movev2System.json";

export const SystemAbis = {
  "system.EncounterFlee": EncounterFleeSystem.abi,
  "system.EncounterThrow": EncounterThrowSystem.abi,
  "system.JoinGame": JoinGameSystem.abi,
  "system.JoinGamev2": JoinGamev2System.abi,
  "system.Mark": MarkSystem.abi,
  "system.Move": MoveSystem.abi,
  "system.Movev2": Movev2System.abi,
};
